version: "3.0"

services:
  frontend:
    build:
      context: src/frontend
    links:
      - "api:api"
    ports:
      - "3000:3000"
    volumes:
      - "./src/frontend:/src"
    command: ["yarn", "start"]

  api:
    build:
      context: src/api
    links:
      - "db:db"
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://madhouse_platform:madhouse_platform@db/madhouse_platform"
    volumes:
      - "./src/api:/src"
    command: ["yarn", "dev"]

  agent:
    build:
      context: src/agent
    links:
      - "api:api"
    volumes:
      - "./src/agent:/src"

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: madhouse_platform
      POSTGRES_PASSWORD: madhouse_platform
      POSTGRES_DB: madhouse_platform
